const marvel = {
  data: {
    results: [
      {
        id: 214,
        title: "Thor: Vikings (2003) #4",
        description:
          "Thor and Dr. Strange go back through time to gather a force to face the ZOMBIE VIKINGS!!",
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/9/b0/4bc6a74872f5c.jpg",
        characters: "Thor",
      },
      {
        id: 169,
        title: "The Eternal (2003) #6",
        description:
          "The shocking series conclusion! A devastating clash between Eternals and Celestials leaves no one unchanged... and has consequences of cosmic proportions!",
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/6/30/4bc6aa9841830.jpg",
        characters: 0,
      },
      {
        id: 298,
        title: "Epic Anthology (2004)",

        description:
          "The debut of a new quarterly anthology series spotlighting the best full-length EPIC stories submitted by up-and-coming 0! Issue #1 features:\r\nSTRANGE MAGIC pt. 1 by Jason Henderson & Greg Scott\r\nYOUNG ANCIENT ONE pt. 1 by Rob Worley & Andy Kuhn\r\nSLEEPWALKER pt. 1 by Robert Kirkman & Khary Randolph\r\n72 PGS./MARVEL PSR...$5.99",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/e/c0/4bc6a0e0a59be.jpg",

        characters: 0,
      },
      {
        id: 382,
        title: "Hulk: Nightmerica (2003) #5",
        description:
          "The finest minds in the world have tried and failed to cure Bruce Banner of the awful curse of the Hulk. But, perhaps, at long last, in the depths of the Nightmerica Compound, that long sought cure may have finally been found. But is it simply an act of pure benevolence, or is there a hidden agenda behind it all?\r\n[This is a resolicitation, all previous orders are cancelled.]\r\n32 PGS./MARVEL PSR...$2.99",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/9/80/4bc32e72ef664jpg",
        characters: "Hulk",
      },
      {
        id: 388,
        title: "4 (2004) #2",
        description:
          "Comics' first family face their most personal and unpredictable crisis yet in this debut of their new edgy MARVEL KNIGHTS ongoing series. Writer Roberto Aguirre-Sacasa and rising-superstar artist Steve McNiven pit the Fantastic Four against a challenge the likes of which they've never faced, and to overcome it they'll need to call on the same humor, determination and family bonds that have delivered them from danger time and time again.\r<br>This is the FF ... the 4 ... like you've never seen them before!\r<br>32 PGS.(each)/MARVEL PSR...$2.99",
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/6/c0/5841c1ff8563c.jpg",
        characters: [
          {
            name: "Fantastic Four",
          },
          {
            name: "Human Torch",
          },
          {
            name: "Invisible Woman",
          },
          {
            name: "Thing",
          },
        ],
        returned: 4,
      },
      {
        id: 7,
        title: "Art of Marvel Vol. 2 (Hardcover)",
        description:
          "This brand-new deluxe hardcover is a follow-up to the best-selling ART OF MARVEL VOL. I. Featuring more than 100 illustrations by the comic book industry's hottest artists and painters, this new volume features more breathtaking looks at your favorite Marvel heroes and villains, including Spider-Man, the X-Men, the Hulk, Daredevil, Elektra, the Punisher, the Avengers and many, many more! A perfect companion piece to ART OF MARVEL VOL. I, this deluxe coffee-table book showcases the rich artistry of the Marvel Universe like never before!",
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/f/10/4c7d67f1ba2da.jpg",
        characters: 0,
      },
      {
        id: 182,
        title: "Supreme Power (2003) #3",
        description:
          'When reports of a secretive government project "Hyperion" begin to surface in shadowy circles, investigative reporter Jason Scott starts to see a connection. And when he tracks down a woman who swears that she and her husband found a baby who crash-landed a spaceship in a cornfield, he thinks he has found the key.  What will the government do if he uncovers their secret super hero?  Will they let Jason continue to uncover details ... or will they silence him?',
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/b/c0/4bc6a90fa02b7.jpg",
        characters: 0,
      },
      {
        id: 191,
        title: "Spider-Girl (1998) #67",
        description:
          "Spider-Girl learns that sometimes you just have to take one for the team when she loses one regular cast member, grows more distant from a second and learns something terrible about a third.",
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/2/f0/4bc6a8e9edfd5.jpg",
        characters: [
          {
            name: "Spider-Girl (May Parker)",
          },
        ],
      },
      {
        id: 10,

        title: "Mystique (2003) #21",

        description:
          "Mystique is caught between two masters-one, mutant activist Charles Xavier; the other, the mysterious Quiet Man. Now, the time has come when she can no longer serve both!",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/1/50/580fe48216977.jpg",

        characters: [
          {
            name: "Mystique",
          },
        ],
      },
      {
        id: 296,

        title: "Spider-Man/Doctor Octopus: Negative Exposure (2003) #3",

        description:
          "The sinister plans of Doc Ock slowly simmer through the bars of Riker's Island as Spider-Man comes face-to-face with Peter Parker's arch-nemesis. An action-packed issue also featuring a mysterious guest appearance from one of Spider-Man's most dreaded foes.",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/2/f0/5d24f707b1611.jpg",

        characters: [
          {
            name: "Doctor Octopus",
          },
          {
            name: "Spider-Man (Peter Parker)",
          },
        ],
      },
      {
        id: 291,
        title: "Ant-Man (2003) #1",
        description:
          "Size does matter.  And no one knows this more than Hank Pym - a.k.a. Ant-Man. Got a problem with Galactus? Call the FF. Got a problem with, say, mind-controlled cockroaches? Then Ant-Man's your man! And needless to say, it's done a number on our diminutive hero's self-esteem.  When Ant-Man is tapped to infiltrate an international spy ring that has been siphoning secrets out of Washington, he jumps at the chance - unaware that he's being used as a pawn in a larger game of espionage.",
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/6/e0/4bc6a2497684e.jpg",
        characters: 0,
      },
      {
        id: 260,
        title: "Wolverine/Captain America (2004) #1",
        description:
          "It's a Marvel team-up for the ages in this 4-issue weekly limited series event! When a highly coveted piece of alien Shi'Ar technology en route from the X-Men's headquarters to Avengers Mansion gets intercepted by a rogue group of ex-S.H.I.E.L.D. super agents, both teams send their best chance to get it back into the field! Can these two VERY different heroes work together for a common cause?",
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/b/d0/5dbae9405b1d2.jpg",
        characters: [
          {
            name: "Captain America",
          },
          {
            name: "Iron Man",
          },
          {
            name: "Wolverine",
          },
        ],
      },
      {
        id: 244,
        title: "Weapon X (2002) #15",
        description:
          "An X-MAN joins the WEAPON X team in this start of a new story arc!",
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/9/a0/5944049d1edfb.jpg",
        characters: [
          {
            name: "Chamber",
          },
          {
            name: "Cyclops",
          },
          {
            name: "Husk",
          },
          {
            name: "Iceman",
          },
          {
            name: "Weapon X",
          },
          {
            name: "Wolverine",
          },
          {
            name: "X-Men",
          },
        ],
      },
      {
        id: 355,
        title: "Spider-Man/Doctor Octopus: Negative Exposure (2003) #4",
        description:
          "Will Doc Ock be successful in his brutal manipulation of naïve cameraman Jeff Brasi - Peter Parker's main rival at the Bugle - or will the plan blow up in his face?",
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/6/90/5d25e408b807f.jpg",
        characters: [
          {
            name: "Doctor Octopus",
          },
          {
            name: "Spider-Man (Peter Parker)",
          },
        ],
      },
      {
        id: 312,
        title: "Emma Frost (2003) #4",
        description:
          "Vacationing with her family in Peru, young Emma Frost discovers her newfound mutant powers aren't the only secret that her family is keeping! The perils and thrills of being a mutant set in as Emma slowly blossoms into the dangerous and seductive X-Man of today!",
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/f/30/5e28a2fad25cf.jpg",
        characters: [
          {
            name: "Emma Frost",
          },
        ],
      },
      {
        id: 293,
        title: "Crimson Dynamo (2003) #6",
        description:
          "The terrible truth about the Crimson Dynamo armor is out, and The Konsortium emerges to seize power when Russia falls! And it may be beyond Gennady and his American friends to stop it!",
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/f/30/4bc6a0f39f2bf.jpg",
        characters: [
          {
            name: "Crimson Dynamo",
          },
        ],
      },
      {
        id: 390,
        title: "Crimson Dynamo (2003) #4",
        description:
          "The renegade Crimson Dynamo and its hunters converge on Moscow - and on Gennady Gavrilov, who's desperately trying to avert disaster. Did the armor's creator hide the key to stopping the metal monstrosity - and a growing international crisis?",
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/2/f0/4bc69b0151292.jpg",
        characters: [
          {
            name: "Crimson Dynamo",
          },
        ],
      },
      {
        id: 309,
        title: "Crimson Dynamo (2003) #5",
        description:
          "The Soviet Union has already fallen, can young Gennady Gavrilov - on the run for his very life - keep the walking weapon of mass destruction from destroying Russia altogether?",
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/b/d0/4bc6a0b0e81d8.jpg",
        characters: [
          {
            name: "Crimson Dynamo",
          },
        ],
      },
      {
        id: 114,
        title: "Punisher (2001) #33",
        description:
          "It might be The Punisher's final hour as DAREDEVIL, SPIDER-MAN, and WOLVERINE team up to bring Frank Castle's killing spree to an end. And what does the HULK have to do with it all?",
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/8/b0/55bfd704d200c.jpg",
        characters: [
          {
            name: "Punisher",
          },
        ],
      },
      {
        id: 21,
        title: "Starjammers (2004) #6",
        description:
          '"THE CADET AND THE CORSAIRS" EPILOGUE! \r\nThe Starjammers have declared war on the Union of Intelligent Races...but how do they plan to win? The answer might just be in young Tolo Hawk\'s hands."',
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/9/50/564b9ae8a2e31.jpg",
        characters: [
          {
            name: "Starjammers",
          },
        ],
      },
      {
        id: 264,
        title: "Venom (2003) #11",
        description:
          "Certain questions have arisen since Venom's mysterious appearance at the Radar Station in Northern Canada. Like, how did he get there? Where's Eddie Brock? And, what turned this one-time \"Lethal Protector\" into a bloodthirsty homicidal maniac? The answers to these questions will be revealed with the help of a few guest stars.",
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/a/40/56c38e27e9cc8.jpg",
        characters: 0,
      },
      {
        id: 247,
        title: "Spider-Girl (1998) #69",
        description:
          "\"TRUTH\" pt. 1 (of 2)\r<br>Doctor Octopus is back - and we don't mean Otto Octavius! The Man-Wolf returns - and we do mean John Jameson! Secrets are revealed when Mayday Parker finally confronts Brad Miller and Jack Jameson learns the truth about his father's deadly secret!",
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/8/b0/4bc6a43d023c7.jpg",
        characters: [
          {
            name: "Spider-Girl (May Parker)",
          },
        ],
      },
      {
        id: 25,
        title: "Punisher Max (2004) #13",
        description:
          "\"MOTHER RUSSIA\" PART 1 (OF 6)\r\nNicky Fury's got a job that needs doing - in Russia.  The kind of suicide mission any sane man wouldn't ponder for a second.  And that's exactly why he needs Frank Castle.",
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/3/40/4bc6b56815504.jpg",
        characters: [
          {
            name: "Punisher",
          },
        ],
      },
      {
        id: 26,
        title: "Punisher Max (2004) #14",
        description:
          "\"MOTHER RUSSIA\" PART 2 (OF 6)\r<br>Nicky Fury's got a job that needs doing - in Russia.  The kind of suicide mission any sane man wouldn't ponder for a second.  And that's exactly why he needs Frank Castle.\r<br>",
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/5/e0/4bc6b5635a251.jpg",
        characters: [
          {
            name: "Punisher",
          },
        ],
      },
      {
        id: 115,
        title: "Punisher Max (2004) #3",
        description:
          "An old acquaintance - with in-depth knowledge of Frank Castle's modus operandi - is after the Punisher. And what he has in store for Frank cuts far deeper than mere revenge.",
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/f/60/4bc6ad5fb6e36.jpg",
        characters: [
          {
            name: "Punisher",
          },
        ],
      },
      {
        id: 119,
        title: "NYX (2003) #2",
        description:
          "As the struggle to survive adolescence becomes more intense, Alphabet City's newest mutant begins to understand how her powers can save her butt.   But what will she do when she learns that self-preservation comes at a price?",
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/7/70/5d49e4ef78544.jpg",
        characters: 0,
      },
      {
        id: 328,
        title: "Spider-Man/Doctor Octopus: Negative Exposure (2003) #5",
        description:
          "Preparing for his most vicious confrontation with Spider-Man, Doc Ock unleashes a torrent of destruction and mayhem on the unsuspecting citizens of Manhattan! Has cameraman Jeff Haight gone too far in his quest for the perfect shot?\r\n32 PGS./MARVEL PSR...$2.99",
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/f/70/5d25eaac7b7c9.jpg",
        characters: [
          {
            name: "Doctor Octopus",
          },
          {
            name: "Spider-Man (Peter Parker)",
          },
        ],
      },
      {
        id: 241,
        title: "Weapon X (2002) #18",
        description:
          "\"DEFECTION\" pts. 3 & 4 (of 4)\r\nThe X-Men guest-star as the secrets behind Chamber's recent affiliation with the Weapon X program - and WOLVERINE's mysterious involvement - are uncovered.",
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/7/00/59442e2c8a8c9.jpg",
        characters: [
          {
            name: "Chamber",
          },
          {
            name: "Weapon X",
          },
          {
            name: "Wild Child",
          },
          {
            name: "Wolverine",
          },
        ],
      },
      {
        id: 316,
        title: "Hawkeye (2003) #4",
        description:
          "Hawkeye's Myrtle Beach mystery spirals out of Clint's control just as the little Southern secret worth hundreds of millions of dollars was coming into focus. What was the \"Unity Pact\" that bound a group of Vietnam vets together and is the answer still a world away in Laos? The only way for Clint and a motley band of misfits to find out might be to go on a little road trip...",
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/9/10/5b05b5d9b81c2.jpg",
        characters: [
          {
            name: "Hawkeye",
          },
        ],
      },
      {
        id: 375,
        title: "Avengers (1998) #72",
        description:
          "The She-Hulk is gone, and Jennifer Walters is on the run! Her friends aren't sure what she's afraid of, but they'll find out!",
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/c/c0/586d4eecd44b5.jpg",
        characters: [
          {
            name: "Avengers",
          },
          {
            name: "Captain America",
          },
          {
            name: "Iron Man",
          },
          {
            name: "Scarlet Witch",
          },
          {
            name: "She-Hulk (Jennifer Walters)",
          },
        ],
      },
      {
        id: 212,
        title: "Weapon X (2002) #19",
        description:
          '"COUNTDOWN TO ZERO" pt. 1 (of 3)\r\nMarrow takes center stage! Separated from her former teammates and re-forming a new Gene Nation, will Marrow finally be free from the ghosts of her past? Or will they come back to haunt her?',
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/1/20/59443608a9c67.jpg",
        characters: [
          {
            name: "Chamber",
          },
          {
            name: "Marrow",
          },
          {
            name: "Weapon X",
          },
        ],
      },
      {
        id: 188,
        title: "Spider-Girl (1998) #70",
        description:
          '"TRUTH" pt. 2 (of 2) \r<br>As the Buzz takes on the Man-Wolf and Spider-Girl finds herself pitted against Dr. Jade and the new Dr. Octopus, she gets an assist from the most unexpected source! Featuring cameos by Darkdevil, the Green Goblin & Ladyhawk.',
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/c/90/4bc6a8f842b7c.jpg",
        characters: [
          {
            name: "Spider-Girl (May Parker)",
          },
        ],
      },
      {
        id: 36,

        title: "Spider-Girl (1998) #80",
        issueNumber: 80,
        variantDescription: "",
        description:
          "PART 1 (OF 1) \r<br>A single-issue story and a great jumping-on point for comics' longest-running female headliner!  As Courtney Duran finally learns Moose's terrible secret, Davida Kirby helps an injured Spider-Girl against the monstrous Dragon King.\r<br>",
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/9/80/4bc6b3e5e6158.jpg",
        characters: [
          {
            name: "Spider-Girl (May Parker)",
          },
        ],
      },
      {
        id: 37,
        title: "Marvel Age Fantastic Four (2004) #8",
        description:
          '"PRISONERS OF THE PUPPET MASTER" \r\nEnter the Puppet Master, an evil mastermind who has learned to control people using action figures.  Check out this new all-ages adventure of The Fantastic Four based on the original classic stories!',
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/7/00/57194e8d24f2f.jpg",
        characters: [
          {
            name: "Fantastic Four",
          },
        ],
      },
      {
        id: 329,
        title: "Emma Frost (2003) #8",
        description:
          "Separated from her family for the first time in her life, young Emma finds life on her own growing increasingly more difficult - not to mention dangerous! Emma's new romance is anything but tender as her boyfriend leads them into a precarious situation and she must rely on her burgeoning mental powers to help them escape!",
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/d/03/5908e28811c28.jpg",
        characters: [
          {
            name: "Emma Frost",
          },
        ],
      },
      {
        id: 113,
        title: "Punisher (2001) #34",
        description:
          "\"CONFEDERACY OF DUNCES\" \r\n\r\nIt might be The Punisher's final hour as DAREDEVIL, SPIDER-MAN, and WOLVERINE team up to bring Frank Castle's killing spree to an end. And what does the HULK have to do with it all?",
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/9/d0/55bfdb914e179.jpg",
        characters: [
          {
            name: "Punisher",
          },
        ],
      },
      {
        id: 112,
        title: "Punisher (2001) #35",
        description:
          '"CONFEDERACY OF DUNCES" pts. 3 & 4 (of 5)\r\nWolverine, Spider-Man, and Daredevil continue trying to take down the Punisher!',
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/f/20/55bfdc5ce82a0.jpg",
        characters: [
          {
            name: "Punisher",
          },
        ],
      },
      {
        id: 253,
        title: "Thor: Vikings (2003) #5",
        description:
          "Thor & Dr. Strange have gone back in time to put a team together in hopes of defeating the horrible ZOMBIE VIKINGS that are laying siege to Manhattan!  Can a Viking woman, a Crusader, and a Nazi Fighter Pilot defeat these fearsome foes? ",
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/f/00/4bc6a420bef9c.jpg",
        characters: [
          {
            name: "Thor",
          },
        ],
      },
      {
        id: 360,
        title: "Avengers (1998) #79",
        description:
          "Unexpected tragedy sets superhuman tempers flaring! But sometimes death is just the beginning, and the Wrecking Crew wants Hawkeye to see that for himself!",
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/9/50/586d5a21ecc90.jpg",
        characters: [
          {
            name: "Avengers",
          },
          {
            name: "Captain America",
          },
          {
            name: "Hawkeye",
          },
          {
            name: "Iron Man",
          },
          {
            name: "Scarlet Witch",
          },
          {
            name: "She-Hulk (Jennifer Walters)",
          },
          {
            name: "Wasp",
          },
          {
            name: "Wrecking Crew",
          },
          {
            name: "Yellowjacket (Hank Pym)",
          },
        ],
      },
      {
        id: 342,
        title: "Hawkeye (2003) #2",
        description:
          "\"THE HIGH, HARD SHAFT\" pt. 2\r\nA weekend trip to Myrtle Beach. A stripper running away from a tough guy. A vagabond Clint Barton getting involved. The Avenging Archer's new ongoing series continues! Will stirring this beehive of life's losers lead Hawkeye to solving the problem ... or will it get him stung? ",
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/8/90/5b05b4d2b450e.jpg",
        characters: [
          {
            name: "Hawkeye",
          },
        ],
      },
      {
        id: 44,
        title: "Emma Frost (2003) #17",
        description:
          '"BLOOM" PART 5 (OF 6)\r\nEmma has become extremely friendly with another, more experienced telepath...but is this relationship entirely healthy? It might not be for Ian Kendall, the teacher Emma\'s infatuated with...whose life is suddenly turned upside down!',
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/5/e0/5e29cc00350f4.jpg",
        characters: [
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009310",
            name: "Emma Frost",
          },
        ],
      },
      {
        id: 45,
        title: "Amazing Fantasy (2004) #6",
        description:
          "PART 6 (OF 6)It's the end of the origin of Anya Corazon - and a new beginning.  But, first, the question on everyone's mind: what's the public identity of Marvel's newest media darling? Well, we won't tell you here, but we will tell you folks are clamoring for the inside scoop and a glimpse of this amazing spider-like teen, who's now been seen everywhere from Telemundo to Fox News to the NY Daily News - not bad for a Latina from Brooklyn! ",
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/8/f0/6467baa9a060c.jpg",
        characters: [
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009157",
            name: "Spider-Girl (Anya Corazon)",
          },
        ],
      },
      {
        id: 246,
        title: "Weapon X (2002) #13",
        description:
          '"THE UNDERGROUND" concludes! \r\nAmidst betrayals and revelations, in order to survive the agents of Weapon X must choose sides and forge alliances - as the mystery menace among them stands revealed! A storyline so big it needed an extra issue!',
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/9/10/5943ef02beb23.jpg",
        characters: [
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009150",
            name: "Agent Zero",
          },
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009163",
            name: "Aurora",
          },
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009425",
            name: "Marrow",
          },
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009709",
            name: "Weapon X",
          },
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009715",
            name: "Wild Child",
          },
        ],
      },
      {
        id: 219,
        title: "Punisher: The Movie (2004) #1",
        description:
          "Marvel presents the official comic book adaptation of their latest big-screen blockbuster starring John Travolta, Rebecca Romijn-Stamos and Thomas Jane as Frank Castle, the Punisher!",
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/6/70/4bc6a7358f207.jpg",
        characters: 0,
      },
      {
        id: 48,
        title: "Tomb of Dracula (2004) #2",
        description:
          "PART 2 (OF 6)\r\nBlade and a violent team of deadly vampire slayers set out to destroy Dracula before his metamorphosis into a vampire god is complete!! But is there a mole on the mission? Plus: the truth about the eerie prophecy of Dracula's destiny...",
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/2/00/5ebaf9f30bba5.jpg",
        characters: [
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1010677",
            name: "Dracula",
          },
        ],
      },
      {
        id: 367,
        title: "Emma Frost (2003) #5",
        description:
          '"HIGHER LEARNING" pt. 5 (of 6)\r\nEmma\'s vacation is cut short as shocking secrets rock the Frost Family. What startling revelations could be so devastating that a family member is disowned?\r\n32 PGS./MARVEL PSR+...$2.50',
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/9/c0/5e28a752eb3f8.jpg",
        characters: [
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009310",
            name: "Emma Frost",
          },
        ],
      },
      {
        id: 275,
        title: "Wolverine/Captain America (2004) #2",
        description:
          "It's a Marvel team-up for the ages in this 4-issue weekly limited series event! When a highly coveted piece of alien Shi'Ar technology en route from the X-Men's headquarters to Avengers Mansion gets intercepted by a rogue group of ex-S.H.I.E.L.D. super agents, both teams send their best chance to get it back into the field! Can these two VERY different heroes work together for a common cause?",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/e/50/5dbb00d831eaa.jpg",

        characters: [
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009220",
            name: "Captain America",
          },
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009368",
            name: "Iron Man",
          },
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009718",
            name: "Wolverine",
          },
        ],
      },
      {
        id: 346,

        title: "Emma Frost (2003) #6",

        description:
          '"HIGHER LEARNING" CONCLUDES!\r\nEver wonder how and why Emma Frost became the White Queen? This conclusion to the first story arc reveals the life-altering decision young Emma makes, and the dire consequences she must face as a result.\r\n32 PGS./MARVEL PSR+...$2.50',

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/9/20/5e28ac4d3813b.jpg",

        characters: [
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009310",
            name: "Emma Frost",
          },
        ],
      },
      {
        id: 52,

        title: "4 (2004) #12",

        description:
          "\"THE STUFF OF DREAMS\" PART 3 (OF 3)\r\nEvery dream must come to an end-even the fear-induced nightmares that Psycho-Man is spreading across Manhattan!  It's the climax to the first year of Marvel Knights 4 and the final showdown between the FF and their reality-warping foe.  Hold onto your seats - especially you slight Marvelites - that wind blowing is a radical shift in the status quo of Marvel Comics' First Family of super heroes and adventurers!",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/3/80/6467be6c63700.jpg",

        characters: [
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009299",
            name: "Fantastic Four",
          },
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009356",
            name: "Human Torch",
          },
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009366",
            name: "Invisible Woman",
          },
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009459",
            name: "Mr. Fantastic",
          },
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009466",
            name: "Namor",
          },
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009511",
            name: "Psycho-Man",
          },
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009662",
            name: "Thing",
          },
        ],
      },
      {
        id: 143,

        title: "Mystique (2003) #11",

        description:
          "\"MAKER'S MARK\" pt. 1 (of 2)\rMystique's a shape-shifting super-spy that can change literally change her skin. Forge is the mutant inventor who's gotten under her skin. Learn more about their past and present relationship as and find out how the Maker left his mark!!!",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/c/40/580fe1b47a3ed.jpg",

        characters: [
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009465",
            name: "Mystique",
          },
        ],
      },
      {
        id: 54,

        title: "Powerless (2004) #6",

        description:
          "PART 6 (OF 6)\r<br>The mysteries of the Powerless universe are finally revealed in the series' climactic conclusion!  What devastating truth will psychiatrist William Watts learn when the lives of Peter Parker, Matt Murdock and Logan all converge on him for the last time?  In a world without powers, who will live and who will die?  And who will be changed forever?",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/9/00/56b103a87adf3.jpg",

        characters: 0,
      },
      {
        id: 177,

        title: "Supreme Power (2003) #7",

        description:
          'Jump on board one of the biggest hits of the year as it starts a NEW, second major story arc! Another new super power rises out of the "depths" of obscurity - Amphibian! Plus: witness the first (and possibly last!) climactic meeting of Hyperion and Doctor Spectrum!',

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/6/b0/4bc6a92777a45.jpg",

        characters: 0,
      },
      {
        id: 56,

        title: "Marvel Encyclopedia Vol. 6: Fantastic Four (Hardcover)",

        description:
          "The World's Greatest Comic Magazine - for more than five hundred issues, nearly every cover of Fantastic Four has boasted this bold proclamation. Forty years ago, writer Stan Lee and artist Jack Kirby created a team of adventurers like no other that had come before. Now, Marvel Comics is proud to present the definitive guide to this groundbreaking title. Never before has the Fantastic Four's complete history been collected in such a comprehensive volume. This book covers it all, from their first days to the team's landmark 500th issue and beyond!",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/c/60/4bc6b23e498da.jpg",

        characters: 0,
      },
      {
        id: 57,

        title: "Essential Iron Man Vol. 2 (Trade Paperback)",

        description:
          "It's armored action at its best as Iron Man faces Ultimo; the Mandarin; the Titanium Man, the ever-popular communist menace; and more! Guest-starring S.H.I.E.L.D., the Sub-Mariner and the Hulk! Includes the first run of Iron Man's solo series! Collecting TALES OF SUSPENSE #73-99, IRON MAN & SUB-MARINER #1 and IRON MAN #1-10.",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/c/00/4bc6b23923edb.jpg",

        characters: 0,
      },
      {
        id: 180,

        title: "Supreme Power (2003) #5",

        description:
          "THE BLUR steps into the spotlight in the latest issue of  J. Michael Straczynski & Gary Frank's hit new ongoig series! How does this super-speedster fit into this startling and realistic vision of a world being introduced to its first generation of superheroes!?",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/3/70/4bc6a91915931.jpg",

        characters: 0,
      },
      {
        id: 59,

        title: "Marvel Age Spider-Man (2004) #16",

        description:
          "\"THE RETURN OF THE GREEN GOBLIN\" PART 4 (OF 4)\r<br>The kids of Midtown High School throw a celebration in Spider-Man's honor! Could things finally be turning around for our favorite wall-crawler? Don't bet on it! It's the return of Spidey's greatest foe - The Green Goblin! Plus, the Human Torch stops by for a visit. If flames and pumpkin bombs don't get a party started, what does?!",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/1/c0/4bc474b2aadde.jpg",

        characters: [
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009262",
            name: "Daredevil",
          },
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009610",
            name: "Spider-Man (Peter Parker)",
          },
        ],
      },
      {
        id: 391,

        title: "Crimson Dynamo (2003) #3",

        description:
          "Fun turns to terror for Gennady Gavrilov, who realizes he's responsible for the Crimson Dynamo's destructive rampage. The armor's already ruining his life ... Can he stop it before it ends someone else's?",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/e/e0/4bc69afc2c40b.jpg",

        characters: [
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009251",
            name: "Crimson Dynamo",
          },
        ],
      },
      {
        id: 323,
        title: "Ant-Man (2003) #2",

        description:
          "Ant-Man digs deeper to find out who is leaking secret information that threatens our national security.",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/f/20/4bc69f33cafc0.jpg",

        characters: 0,
      },
      {
        id: 170,

        title: "The Eternal (2003) #5",

        description:
          "The final confrontation between Eternals and Celestials grows closer.",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/c/60/4bc6aa93936ea.jpg",

        characters: 0,
      },
      {
        id: 63,

        title: "Venom Vol. 3: Twist (Trade Paperback)",

        description:
          "It's symbiote vs. symbiote, and Spider-Man is forced to play damage control as the two bloodthirsty Venom creatures cause havoc in the city! Patricia Robertson must gain control of the alien symbiote that's eating away at her long enough to kill the original Venom, Eddie Brock. But Spider-Man has other plans and enlists the help of the Fantastic Four. Collecting VENOM #14-18.",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/b/f0/4bc6b225a7d5c.jpg",

        characters: 0,
      },
      {
        id: 288,

        title: "Hulk: Nightmerica (2003) #6",

        description:
          "Revelations abound as the terrible genetic secrets of the Nightmerica experiments are finally revealed! And you won't believe the pivotal role the RAMPAGING HULK plays in the finale.",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/2/10/4bc32e6ddffa2.jpg",

        characters: [
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009351",
            name: "Hulk",
          },
        ],
      },
      {
        id: 286,

        title: "Hawkeye (2003) #3",

        description:
          "\"THE HIGH, HARD SHAFT\" pt. 3\r\nFrom a simple barroom rough-up in Myrtle Beach to beating up Cuban thugs in a Miami elevator, someone is going to a whole lot of trouble to keep the mystery of the 'Unity Tattoo' exactly that. Clint Barton has already gone from intrigued to annoyed ... the next step is angry ... and then anyone in his way better watch out!",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/b/80/5b05b54be04ad.jpg",

        characters: [
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009338",
            name: "Hawkeye",
          },
        ],
      },
      {
        id: 276,

        title: "NYX (2003) #1",

        description:
          "Say hello to a pack of New York City gutterpunks, the likes of which the Marvel Universe has never seen!\r\nThe X-Men's dream has always been one of creating hope from despair - in a young mutant's darkest hour Charles Xavier will always be just around the corner, ready with open arms and a helping hand. But Xavier can't be everywhere at once. What becomes of a group of young mutants that have to rely on themselves for everything from food to shelter to love? Wayward angels with dirty faces who, instead of preparing for Magneto's next big assault, must learn to survive in the cold, harsh world of the city that never sleeps.  \r\nMarvel's own Joe Quesada and superstar-in-waiting Josh Middleton bring the world of the X-Men to the streets, and the struggle for survival has never been more uncertain...",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/7/d0/5d49e3695d88f.jpg",

        characters: 0,
      },
      {
        id: 189,

        title: "Spider-Girl (1998) #68",

        description:
          '"THE RULES"\r\nA stand-alone story features the return of an old super-villain. Spider-Girl notices one of her friends is headed for disaster. Will her efforts to rein him in prove successful or destroy them both?! \r\n32 PGS./ALL AGES...$2.99',

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/c/b0/4bc6a8f3b8d83.jpg",

        characters: [
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009609",
            name: "Spider-Girl (May Parker)",
          },
        ],
      },
      {
        id: 331,

        title: "Gun Theory (2003) #4",

        description:
          "The phone rings, and killer-for-hire Harvey embarks on another hit. But nothing's going right this job. There's little room for error in the business of killing - so what happens when one occurs?\r\n32 PGS./ PARENTAL ADVISORY ...$2.50",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/c/60/4bc69f11baf75.jpg",

        characters: 0,
      },
      {
        id: 229,

        title: "Wolverine/Captain America (2004) #3",

        description:
          "It's a Marvel team-up for the ages in this 4-issue weekly limited series event! When a highly coveted piece of alien Shi'Ar technology en route from the X-Men's headquarters to Avengers Mansion gets intercepted by a rogue group of ex-S.H.I.E.L.D. super agents, both teams send their best chance to get it back into the field! Can these two VERY different heroes work together for a common cause?\r<br>32 PGS. (each)/MARVEL PSR...$2.99 (each)\r<br>",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/8/60/5dc0364abd014.jpg",

        characters: [
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009220",
            name: "Captain America",
          },
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009718",
            name: "Wolverine",
          },
        ],
      },
      {
        id: 348,
        title: "Avengers (1998) #74",

        description:
          '"SEARCH FOR SHE-HULK"\r\n\r\nWhile the Avengers continue to search the globe for her, Jennifer Walters seeks the one person on Earth who can help control her transformations. Featuring the return of the most demanded Avenger of all!\r\n32 PGS.MARVEL PSR...$2.25',

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/3/60/586d530a711f6.jpg",

        characters: [
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1010801",
            name: "Ant-Man (Scott Lang)",
          },
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009165",
            name: "Avengers",
          },
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009220",
            name: "Captain America",
          },
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009338",
            name: "Hawkeye",
          },
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009368",
            name: "Iron Man",
          },
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009562",
            name: "Scarlet Witch",
          },
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009583",
            name: "She-Hulk (Jennifer Walters)",
          },
        ],
      },
      {
        id: 71,

        title: "Hulk & Thing: Hard Knocks (2004) #3",

        description:
          "PART 3 (OF 4)\r<br>It's clobbering ti--OOF!  Bruce Jones and superstar artist Jae Lee ring the bell for round three between two of Marvel's most powerful sluggers.  Kick back and relax with a frosty mug, but make sure your teeth are still in your head.  These fights are so big, even the readers need a mouthpiece!  \r<br>",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/9/50/58dabd5726e12.jpg",

        characters: [
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009351",
            name: "Hulk",
          },
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009662",
            name: "Thing",
          },
        ],
      },
      {
        id: 72,

        title: "Powers (2004) #6",

        description:
          "Kidnapped by super-villains! Tortured by their leader! And she's been missing for hours! \r\nWhat is the fate of Detective Deena Pilgrim??\r\n• Nominated for the Eisner for Best Writer of the Year!",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/1/f0/4bc6b1face0f7.jpg",

        characters: 0,
      },
      {
        id: 73,

        title: "Kabuki (2004) #3",

        description:
          "\"The Alchemy\" Pt. 3\r<br>Kabuki is on a plane leaving Japan, leaving the Noh agency behind.  A new passport, a new name, a new look, a new job, and a new life.  So who is this new character on the plane with her who seems to know so much? \r<br>It's a new start for Kabuki and the perfect jumping on issue for new readers! You've heard about all the awards... You've heard everyone talking about why Kabuki is so amazing and mind-blowing...  Now is the chance to see what all the talk is about!\r<br>",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/b/50/4bc6b0b10b7a6.jpg",

        characters: [
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1011193",
            name: "Kabuki",
          },
        ],
      },
      {
        id: 74,

        title: "Doctor Spectrum (2004) #4",

        description:
          "PART 4 (OF 6)\r<br>Dig deeper into the past of Joe Ledger, A.K.A. Dr. Spectrum! The crystal that powered Hyperion's ship and became embedded in Dr. Spectrum's arm has plans for him. See those plans unfold here, in the story that couldn't be contained in Supreme Power!",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/1/50/4bc6b0ac5dc2a.jpg",

        characters: [
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1010689",
            name: "Doctor Spectrum",
          },
        ],
      },
      {
        id: 75,

        title: "Spider-Man: Enter Doctor Octopus (Trade Paperback)",

        description:
          "An author, editor, television writer, and composer-there is little that Louise Ann Gikow has not done in children's entertainment. She's even spent time on the New York Times best-seller list for  her novelization of The Grinch Who Stole Christmas. Now, she has teamed up with Marvel Press to create a must-read chapter book series starring Spider-Man! Life's hard-welcome to Peter Parker's world! He not only has to do tons of homework and help his Aunt May make ends meet, but also has to battle super villains and save the world. When Doc Ock rolls into town, it spells danger for everyone, especially Peter's best friends, Mary Jane and Harry. And Peter soon learns that the life of a super-hero isn't always so super.",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/9/90/4bc6b0a7993f4.jpg",

        characters: 0,
      },
      {
        id: 396,

        title: "Spider-Girl (1998) #71",

        description:
          "Spider-Girl fights to prevent NYC from being attacked by an army of invisible invaders. Plus: The Buzz finally discovers Spider-Girl's secret identity...or does he?? \r\nGuest-stars J2, DOC MAGUS and STINGER.",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/8/90/4bc69ae4001c2.jpg",

        characters: [
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009609",
            name: "Spider-Girl (May Parker)",
          },
        ],
      },
      {
        id: 376,

        title: "Ant-Man (2003) #3",

        description:
          "When Hank Pym - a.k.a. Ant-Man - is tapped by U.S. Intelligence to infiltrate an international spy ring that has been siphoning secrets out of Washington, the diminutive hero jumps at the chance - unaware that he's being used as a pawn in a larger game of espionage.",
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/d/70/4bc69c7e9b9d7.jpg",

        characters: 0,
      },
      {
        id: 384,

        title: "Gun Theory (2003) #3",

        description:
          "The phone rings, and killer-for-hire Harvey embarks on another hit. But nothing's going right this job. There's little room for error in the business of killing - so what happens when one occurs?\r\n\r\n32 PGS./ PARENTAL ADVISORY ...$2.50",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/c/60/4bc69f11baf75.jpg",

        characters: 0,
      },
      {
        id: 79,

        title: "District X (2004) #7",

        description:
          "\"UNDERGROUND\" PART 1 (OF 6)\r<br>This new arc is a great jumping-on place for new readers to discover the book every X-fan is talking about!  \r<br>Something lives under District X, something that loves the dark...and it's leaving a trail of murders in its wake. In a world that's rarely black-and-white, will Bishop and his partner Ismael be able to make the right calls that save people's lives? Or will they be helpless against this predator under the streets?",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/6/30/583e04b35a8a5.jpg",

        characters: [
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009182",
            name: "Bishop",
          },
        ],
      },
      {
        id: 357,

        title: "Spider-Man/Doctor Octopus: Negative Exposure (2003) #2",

        description:
          "As Doctor Octopus sets his brutal plans for Spider-Man's downfall into motion, the web-slinger is forced to face off with another member of his deadly rogue's gallery - the cold-blooded Vulture!",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/6/40/5d24f31b5565c.jpg",

        characters: [
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009276",
            name: "Doctor Octopus",
          },
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009610",
            name: "Spider-Man (Peter Parker)",
          },
        ],
      },
      {
        id: 81,

        title: "Marvel Age Hulk (2004) #3",

        description:
          '"BIG GREEN MEN" \r\nThe Green Goliath smashes his way through another brand new Marvel Age adventure in the newest SMASH in the Marvel Age line! Bruce Banner continues to wander across the Southwest and finds himself in the town of Roswell, New Mexico, where things aren\'t always what they seem. Will the Hulk be able to stop an alien threat from invading Earth? Find out in this never-before-told Hulk adventure in the thrilling Marvel Age manner!',
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/8/a0/5a7b2366b0e1a.jpg",

        characters: [
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009351",
            name: "Hulk",
          },
        ],
      },
      {
        title: "Mystique (2003) #9",

        description:
          '"TINKER, TAILOR, MUTANT, SPY" pt. 3 (of 4)\r\nMystique is on the trail of a woman who is a walking plague... and who has stolen a deadly biological weapon!\r\n32 PGS./MARVEL PSR...$2.99',

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/6/10/580fe5611b16.jpg",

        characters: [
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009465",
            name: "Mystique",
          },
        ],
      },
      {
        id: 144,

        title: "Mystique (2003) #10",
        description:
          '"TINKER, TAILOR, MUTANT, SPY" Concludes!\r\nMystique must save humanity from a deadly, mutated form of smallpox... but will she have to sacrifice the life of her loyal field handler, Shortpack, for the greater good?',

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/a/20/580fe18bd986c.jpg",

        characters: [
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009465",
            name: "Mystique",
          },
        ],
      },
      {
        id: 84,

        title:
          "MARVEL MASTERWORKS: GOLDEN AGE CAPTAIN AMERICA VOL. 1 HC VARIANT (Hardcover)",

        description:
          "Continuing the celebration of its 65th anniversary, Marvel Comics is proud to re-present the earliest adventures of Captain America, Sentinel of Liberty! This monumental hardcover volume re-masters and restores the first four historic issues of Captain America from 1941. Return to the Golden Age of comics as Cap and Bucky come face to face with the Red Skull, the Ringmaster of Death, Nazi minions and more!",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/c/f0/4bc6b07fc987e.jpg",

        characters: 0,
      },
      {
        id: 156,

        title: "Ultimate Six (2003) #3",

        description:
          "The Six has escaped their S.H.I.E.L.D. holding pen, and the outlines of Norman Osborn's horrific scheme become apparent. The Ultimates line up against them! But where is Ultimate Spidey?",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/b/d0/4bc6aad4280c6.jpg",

        characters: 0,
      },
      {
        id: 111,

        title: "Punisher (2001) #36",

        description:
          '"CONFEDERACY OF DUNCES" pts. 3 & 4 (of 5)\r\nWolverine, Spider-Man, and Daredevil continue trying to take down the Punisher!',

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/c/30/55c0fc1d289ca.jpg",

        characters: [
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009515",
            name: "Punisher",
          },
        ],
      },
      {
        id: 394,

        title: "Agent X (2002) #15",

        description:
          "FINAL ISSUE!  \r\nIt's the end of the road for AGENT X (yeah, we know ... but for real this time) ... but could that ending mean a new beginning for the long-lost merc known as Deadpool? And what will be the final fate of the man named Alex Hayden?",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/e/20/5977661368a33.jpg",

        characters: [
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1011031",
            name: "Agent X (Nijo)",
          },
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009268",
            name: "Deadpool",
          },
          {
            resourceURI:
              "http://gateway.marvel.com/v1/public/characters/1009648",
            name: "Taskmaster",
          },
        ],
      },
      {
        id: 228,
        title: "Wolverine/Captain America (2004) #4",
        description:
          "It's a Marvel team-up for the ages in this 4-issue weekly limited series event! When a highly coveted piece of alien Shi'Ar technology en route from the X-Men's headquarters to Avengers Mansion gets intercepted by a rogue group of ex-S.H.I.E.L.D. super agents, both teams send their best chance to get it back into the field! Can these two VERY different heroes work together for a common cause?",
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/6/c0/5dc036c6929a8.jpg",
        characters: [
          {
            name: "Captain America",
          },
          {
            name: "Wolverine",
          },
        ],
      },
      {
        id: 89,
        title: "Official Handbook of the Marvel Universe (2004) #7",
        description:
          "The House of Ideas pays tribute to its fallen heroes! OHOTMUBOTD04 includes in-depth bios on more than 40 of Marvel's dearly departed - from ancient ones, old soldiers, kid sidekicks and Stacys to casualties of THE comic-book event of 2004: Avengers Disassembled! Plus: an all-new, digitally painted cover by superstar artist Salvador Larroca!",
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/8/80/4bc6b06c450c1.jpg",
        characters: [
          {
            name: "Hawkeye",
          },
          {
            name: "Thor",
          },
        ],
      },
      {
        id: 315,

        title: "Gun Theory (2003) #2",

        description:
          "The phone rings, and killer-for-hire Harvey embarks on another hit. But nothing's going right this job. There's little room for error in the business of killing - so what happens when one occurs?",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/9/60/4bc69f4f331b4.jpg",

        characters: 0,
      },
      {
        id: 352,

        title: "Human Torch (2003) #7",

        description:
          "\"A PLAGUE OF LOCUSTS\" pt. 1 (of 2)\r\nJohnny finds himself in the war-torn Balkans in a mysterious castle filled with dark secrets and deadly phantoms. It's the biggest fight of the Torch's life - because this time what he can't see... CAN kill him!",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/f/f0/4bc69d7ade57e.jpg",

        characters: [
          {
            name: "Human Torch",
          },
        ],
      },
      {
        id: 181,

        title: "Supreme Power (2003) #4",

        description:
          "Who is the Whizzer and what does he have to do with Hyperion? All this and Nighthawk strikes!",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/c/80/4bc6a91497aec.jpg",

        characters: 0,
      },
      {
        id: 93,

        title: "Powers Vol. 7: Forever (Trade Paperback)",

        description:
          "FOREVER!  The comic experience of the year - the origin of POWERS! \r<br>FOREVER! The story that literally spans the history of man as all the mysteries of Powers and the Powers universe unfold, following a lone warrior's trek through the greatest stories ever told. \r<br>FOREVER!  The largest Powers collection yet!\r<br>WE SAID, \"FOREVER!\" WITH EXCLUSIVE BONUS FEATURES!! GET: the entire unedited script to the controversial Powers #31, another brand new \"Bendis and Oeming interview each other,\" a stunning look into Oeming's research and sketch work for every era, bonus text pieces, a cover gallery, a making of the scene, and much more. We'd tell you, but we're already out of breath!\r<br>",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/6/20/4bc6b0591b249.jpg",

        characters: 0,
      },
      {
        id: 117,

        title: "Punisher Max (2004) #2",

        description:
          "\"IN THE BEGINNING\" pts. 1 & 2\r\n<br>Garth Ennis finally lets loose to take Punisher to the MAX - literally - as the hunter becomes the hunted! No more pulled punches, no more dialing it down. One of comics' most provocative writers takes one of comics' most provocative characters in a new direction - ANY direction he wants!\r\n<br>32 PGS. (each)/PARENTAL ADVISORY...$2.99 (each)",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/b/b0/4bc6ad5660ca1.jpg",

        characters: [
          {
            name: "Punisher",
          },
        ],
      },
      {
        id: 227,

        title: "Wolverine: Snikt! (2003) #5",

        description:
          "Wolverine attempts a last ditch effort to defeat the evil Mandate aliens in this conclusion to the hit mini-series. But if he does escape with his life, will he be able to find his way back to his own era?\r\n32 PGS./MARVEL PG ...$2.99",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/1/d0/4bc32ea7a9abd.jpg",

        characters: [
          {
            name: "Wolverine",
          },
        ],
      },
      {
        id: 183,

        title: "Startling Stories: The Incorrigible Hulk (2004) #1",

        description:
          "For Doctor Bruce Banner life is anything but normal. But what happens when two women get between him and his alter ego, the Incorrigible Hulk? Hulk confused! \r\nIndy superstar Peter Bagge (THE MEGALOMANIACAL SPIDER-MAN) takes a satirical jab at the Hulk mythos with a tale of dames, debauchery and destruction.",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available.jpg",

        characters: [
          {
            name: "Hulk",
          },
        ],
      },
      {
        id: 97,

        title: "Punisher (2001) #37",

        description:
          '"CONFEDERENCY OF DUNCES" CONCLUDES!  \r\nThe climactic conclusion to this fun superhero sendoff! It\'s a battle royale as the Punisher takes on Spider-Man, Daredevil & Wolverine. But whose side is the Hulk on?',

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/8/b0/55c1020dcb77c.jpg",

        characters: [
          {
            name: "Punisher",
          },
        ],
      },
      {
        id: 292,

        title: "Avengers (1998) #78",
        description:
          "The Wrecking Crew has Captain America near death, with only one unlikely hero to defend him! Who will live, and who must be avenged?",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/a/70/586d58cab59e9.jpg",

        characters: [
          {
            name: "Avengers",
          },
          {
            name: "Captain America",
          },
          {
            name: "Hawkeye",
          },
          {
            name: "Iron Man",
          },
          {
            name: "Scarlet Witch",
          },
          {
            name: "She-Hulk (Jennifer Walters)",
          },
          {
            name: "Wasp",
          },
          {
            name: "Wrecking Crew",
          },
          {
            name: "Yellowjacket (Hank Pym)",
          },
        ],
      },
      {
        id: 160,

        title: "Ultimate Adventures (2002) #6",

        description:
          "The startling conclusion to the series! Woody and Hawk Owl come to a long overdue understanding in their relationship. But, does the truth come a bit too late?",
        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/c/a0/5a8ecc6c0b885.jpg",

        characters: [
          {
            name: "Captain America (Ultimate)",
          },
          {
            name: "Giant-Man (Ultimate)",
          },
          {
            name: "Iron Man (Ultimate)",
          },
          {
            name: "Thor (Ultimate)",
          },
          {
            name: "Ultimates",
          },
          {
            name: "Wasp (Ultimate)",
          },
        ],
      },
      {
        id: 179,

        title: "Supreme Power (2003) #6",

        description:
          "Featuring the historic first meeting between the two deadliest men on the planet - Hyperion & Nighthawk!\r\n32 PGS./PARENTAL ADVISORY...$2.99",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/9/30/4bc6a91de0546.jpg",

        characters: 0,
      },
      {
        id: 374,

        title: "Avengers (1998) #77",

        description:
          "The Avengers vs. the Wrecking Crew in England! Earth's mightiest heroes should go over big with the British, especially when the Wasp is hundreds of feet high!",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/a/80/586d5785dfbc8.jpg",

        characters: [
          {
            name: "Avengers",
          },
          {
            name: "Captain America",
          },
          {
            name: "Hawkeye",
          },
          {
            name: "Wasp",
          },
          {
            name: "Wrecking Crew",
          },
        ],
      },
      {
        id: 102,

        title: "Sentinel (2003) #11",

        description:
          "\"AWAKENING\" pt. 2 (of 3)\r\nIf it wasn't enough for Juston to have a family member in the hospital and the authorities breathing down his neck, now he has to contend with a 30-foot-tall robot that's become aware of its true purpose - to hunt and kill mutants!",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/6/d0/6467bb53cf907.jpg",

        characters: [
          {
            name: "Sentinel",
          },
        ],
      },
      {
        id: 243,

        title: "Weapon X (2002) #17",

        description:
          "\"DEFECTION\" pts. 3 & 4 (of 4)\r\nThe X-Men guest-star as the secrets behind Chamber's recent affiliation with the Weapon X program - and WOLVERINE's mysterious involvement - are uncovered.",

        thumbnail:
          "http://i.annihil.us/u/prod/marvel/i/mg/1/10/594425d853b49.jpg",

        characters: [
          {
            name: "Chamber",
          },
          {
            name: "Cyclops",
          },
          {
            name: "Iceman",
          },
          {
            name: "Weapon X",
          },
          {
            name: "Wolverine",
          },
        ],
      },
    ],
  },
};
